version: '3'
services:
    test:
        build:
            context: .
            dockerfile: Dockerfile-dev
        ports:
            - "80:80"
        volumes:
            - ".:/app"
    redis:
        image: "redis:3.2.4"
        container_name: ads_manager_redis
        ports:
            - "6380:6379"
        volumes:
            - redis-datavolume:/data
    postgres:
        image: "mdillon/postgis:9.6"
        container_name: ads_manager_postgres
        restart: on-failure
        ports:
            - "5435:5432"
        volumes:
            - postgres-datavolume:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test
    mysql:
        image: "mysql:5.6"
        container_name: ads_manager_mysql
        restart: on-failure
        ports:
            - "3346:3306"
        volumes:
            - mysql-datavolume:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
volumes:
    redis-datavolume:
    mysql-datavolume:
    postgres-datavolume: